language: python


python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies
install:
    pip install -r dev-requirements.txt
# command to run tests
script: coverage run --source schematics -m py.test

after_success:
    coveralls
